### ISSUE TITLE
Publish symbols as well as binary

### ISSUE THREAD

**Issue by AccaliaDeElementia** [aeberhardo/phantomjs-linux-armv6l#1]
Having issue with crashes on Raspberry pi that i can't reproduce on x64 hardware. need symbols to produce reliable stack trace for proper debugging.

according to https://github.com/ariya/phantomjs/wiki/Crash-Reporting using the script `deploy/build-and-package.sh` should generate both binary and symbols

**Comment by aeberhardo** [comment]
I'll look into this when I'm going to build PhantomJS 1.9.

**Comment by AccaliaDeElementia** [comment]
When you do the build note that the noted script is a replacement for `./build.sh` not a supplementary.

it runs build.sh with some special arguments as the first step.

Should save yourself about 30 hours of waiting while the Raspberry pi compiles, only to need to compile again because the debug symbols are not usually generated by `build.sh`

**Comment by aeberhardo** [comment]
Thanks, I will heed your advice.

**Comment by aeberhardo** [comment]
I just started `build-and-package.sh`. I wonder how long it is going to take.

**Comment by AccaliaDeElementia** [comment]
it's been running on my pi for about 20 hours so far. i think it's close to being done.

If successful I'll fork and issue a pull request.

**Comment by aeberhardo** [comment]
great, thanks a lot! when you're ready you can fork the branch "1.9" that i have prepared for this.

**Comment by AccaliaDeElementia** [comment]
Issued pull request for the 1.9.0 binary. still working on debug symbols. script failed (22 hours in) with error below. I'm looking into it.

`src/tools/linux/md2core/minidump-2-core.cc:327:2: error: #error "This code has not been ported to your platform yet"
src/tools/linux/md2core/minidump-2-core.cc:385:2: error: #error "This code has not been ported to your platform yet"
src/tools/linux/md2core/minidump-2-core.cc:142:3: error: ‘user_regs_struct’ does not name a type
src/tools/linux/md2core/minidump-2-core.cc:198:5: error: ‘user_regs_struct’ does not name a type
src/tools/linux/md2core/minidump-2-core.cc:199:5: error: ‘user_fpregs_struct’ does not name a type
src/tools/linux/md2core/minidump-2-core.cc: In function ‘void ParseThreadList(CrashedProcess*, const google_breakpad::MinidumpMemoryRange&, const goo
gle_breakpad::MinidumpMemoryRange&)’:
src/tools/linux/md2core/minidump-2-core.cc:354:71: error: ‘ParseThreadRegisters’ was not declared in this scope
src/tools/linux/md2core/minidump-2-core.cc: In function ‘bool WriteThread(const CrashedProcess::Thread&, int)’:
src/tools/linux/md2core/minidump-2-core.cc:673:14: error: ‘struct prstatus’ has no member named ‘pr_reg’
src/tools/linux/md2core/minidump-2-core.cc:673:30: error: ‘const struct CrashedProcess::Thread’ has no member named ‘regs’
src/tools/linux/md2core/minidump-2-core.cc:673:43: error: ‘user_regs_struct’ was not declared in this scope
src/tools/linux/md2core/minidump-2-core.cc:686:26: error: ‘user_fpregs_struct’ was not declared in this scope
src/tools/linux/md2core/minidump-2-core.cc:690:26: error: ‘const struct CrashedProcess::Thread’ has no member named ‘fpregs’
src/tools/linux/md2core/minidump-2-core.cc: In function ‘int main(int, char**)’:
src/tools/linux/md2core/minidump-2-core.cc:1006:21: error: ‘ELF_ARCH’ was not declared in this scope
src/tools/linux/md2core/minidump-2-core.cc:1023:48: error: ‘user_fpregs_struct’ was not declared in this scope`

**Comment by aeberhardo** [comment]
Thanks for the pull request, much appreciated. I've merged the binary to the 1.9 branch.
In about 16 hours I can tell if the debug symbols work with my compile.

**Comment by AccaliaDeElementia** [comment]
I can actually tell you right now that it won't. 

the build error comes from `src/breakpad/tools/linux/md2core/minidump-2-core.cc` it does a `#error` if the target architecture is not `i386` or `x86_64`.  It also fails to define the functions `ParseThreadRegisters`, `ParseThreadList` and a few necessary structs.

breakpad itself has supported the ARM architecture since 2010, so it's not an error inherent in breakpad. I think i can work out something, or at least open a bug upstream in phantomjs.

**Comment by AccaliaDeElementia** [comment]
actually scratch that. while Google breakpad in general supports the ARM architecture the minidump tool does not.

Probably due to the vast differences between versions of ARM. I'll still see what i can do, but if Google hasn't figured out how to support ARM for this i doubt I will be able to come up with anything they haven's already tried.

**Comment by aeberhardo** [comment]
too bad. but i really appreciate your efforts.

**Comment by AccaliaDeElementia** [comment]
No problem. I'll pick at the debug symbols issue for a little longer and see what i come up with.

However since 1.9 seems to have done away with the segfault that was plaguing me I'm going to go ahead and mark this issue closed, we can re-open if i come up with something or someone else has an issue that needs the debug symbols.

**Comment by aeberhardo** [comment]
Glad to hear your segfault issue was solved by 1.9. I've merged 1.9 to master now.
