### ISSUE TITLE
Poodle

### ISSUE THREAD

**Issue by alex-reiter** [aeberhardo/phantomjs-linux-armv6l#11]
Please update to phantomjs version >=1.9.8 [1] where SSLv3 is no longer the default SSL protocol [2].

References
[1] https://github.com/ariya/phantomjs/issues/12655
[2] http://phantomjs.org/api/command-line.html

**Comment by nanderh** [comment]
Got a couple newer builds available in my fork: https://github.com/nanderh/phantomjs-linux-armv6l

**Comment by aeberhardo** [comment]
Please have a look at https://github.com/spfaffly/phantomjs-linux-armv6l for a current PhantomJS 2.0 build. Updated compiling instructions can be found at https://www.bitpi.co/2015/02/11/compiling-phantomjs-on-raspberry-pi/. Thanks to @spfaffly for the effort.
