### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by nanderh** [aeberhardo/phantomjs-linux-armv6l#9]
Build process error, don't have a specific error anymore but fixed it by installing libfxt-dev as suggested by https://groups.google.com/forum/#!msg/phantomjs/7AoQB_Q5GqM/w6HwGN7mJh8J

**Comment by aeberhardo** [comment]
Thanks a lot! I will add your finding to the build instructions.

**Comment by nanderh** [comment]
And on a different note, I will compile either weekly when there are many new commits or as soon as there are any updates to their master branch to provide a "nightly" build.

**Comment by aeberhardo** [comment]
@nanderh Thanks a lot for your help. Much appreciated!
